### ISSUE TITLE
Improve mapping : fields are wrong sometimes from generated `ExtractedOrder` object

### ISSUE THREAD

**Issue by siddhantmaitra** [siddhantmaitra/swiggy-export#10]
Fields such as : 
- platform fees
- discount applied
- price
- quantity

Are sometimes missing or incorrectly mapped. Mapping function should be made more flexible to handle various response structures from upstream

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the extractOrderInfo function to handle missing or incorrectly mapped fields such as platform fees, discount applied, price, and quantity. The function now uses optional chaining and fallback values to ensure more robust mapping of these fields.

You can review changes in this commit: https://github.com/mnmnk43434/siddhantmaitra-swiggy-export-10/commit/250b024c96789a214176a285e140158d25c73b9e.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
